file:
    ip: localhost

server:
    port: 9090

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ENC(o28HrM4RMgw/4ALoOyHTIA==)
        password: ENC(EH6vQZ34/FflaZhyEEeKJA==)
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3309/ACM?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    servlet:
        multipart:
            max-file-size: 100MB

#mybatis-plus 日志配置
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

interceptor-config:
    excludePathPatterns:
        - /doc.html
        - /webjars/**
        - /swagger-resources/**
        - /frontLogin
        - /backgroundLogin
        - /error
        - /
        - /csrf

jasypt:
    encryptor:
        # 配置加密算法
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator
        property:
            # 算法识别前缀(当算法发现配置文件中的值以这前缀开始，后缀结尾时，会使用指定算法解密)
            prefix: ENC(
            # 算法识别后缀
            suffix: )


