file:
    ip: localhost

server:
    port: 9090

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 990324
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3309/springboot-vue?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
        username: root
    servlet:
        multipart:
            max-file-size: 100MB

#mybatis-plus 日志配置
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

interceptor-config:
    excludePathPatterns:
        - /doc.html
        - /webjars/**
        - /swagger-resources/**
        - /frontLogin
        - /backgroundLogin
        - /error
        - /
        - /csrf

